- name: Installing dependencies
  hosts: web
  become: true
  tasks:
    - name: install dependencies
      apt: pkg={{ item }} state=present install_recommends=no
      with_items:
        - build-essential
        - git
        - libcurl4-openssl-dev
        - libffi-dev
        - libreadline-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
        - build-essential 
        - libyaml-dev 
        - openssl 
        - curl 
        - git-core 
        - bison 
        - libcurl4-openssl-dev 
        - libsqlite3-dev 
        - sqlite3 
        - python-software-properties
