- name: Installing Ruby with rbenv
  hosts: web
  vars:
    rbenv_exe: "{{user_dir}}/.rbenv/bin/rbenv"
    target_ruby_version: "2.3.1"
  tasks:
    - name: check if target ruby version is installed
      command: "{{rbenv_exe}} version"
      register: current_ruby_version

    - name: install ruby version {{ target_ruby_version }}
      command: "{{rbenv_exe}} install {{ target_ruby_version }}"
      when: target_ruby_version not in current_ruby_version.stdout

    - name: set global ruby version as {{ target_ruby_version }}
      command: "{{rbenv_exe}} global {{ target_ruby_version }}"
      when: target_ruby_version not in current_ruby_version.stdout

